## Numpy

NumPy is a general purpose array-processing pacakge. It provides a high-erformance multidimensional array object, and tools for working with these arrays. It is the fundemantal package for scientific computing with python

What is an array?

an array is a data structure that stores values of same data type. In python, this is the main difference between arrays and lists.
while python lists can contain values correspondng to different data types, arrays in python can only conatin values corresponding to sama data type.


In [7]:
## initially lets import numpy

import numpy as np

In [5]:
mylist = [1,2,3,4,5,6,7,8,9,10]

In [6]:
type(mylist)

list

In [8]:
arr = np.array(mylist)

In [5]:
type(arr)

numpy.ndarray

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [19]:
arr.shape # helps to know dimensional of arr

(10,)

In [31]:
arr.reshape(2,5) # helps to convert 1-d to 2-d array, returns a new array without modifying the actual array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [2]:
# multidimensional array
mylist1 = [1,2,3,4,5]
mylist2 = [2,3,4,5,6]
mylist3 = [9,7,6,8,9]

In [3]:
arr2 = np.array([mylist1, mylist2, mylist3])

NameError: name 'np' is not defined

In [25]:
print(arr2)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [27]:
arr2.shape

(3, 5)

In [28]:
arr2.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [29]:
arr2

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [30]:
arr2.shape

(3, 5)

## Indexing

In [33]:
# Accessing the array element

arr3 = np.array([1,2,3,4,5,6,7,8,9])

In [34]:
arr3[4]

5

In [9]:
import numpy as np

In [10]:
# multidimensional array
mylist1 = [1,2,3,4,5]
mylist2 = [2,3,4,5,6]
mylist3 = [9,7,6,8,9]

In [11]:
arr = np.array([mylist1, mylist2, mylist3])

In [12]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [13]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [17]:
arr[:,3:] # skip the x columns

array([[4, 5],
       [5, 6],
       [8, 9]])

In [16]:
arr[1:,] # skip the row

array([[2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [18]:
arr[:1,1:]

array([[2, 3, 4, 5]])

In [19]:
arr[:1,:]

array([[1, 2, 3, 4, 5]])

In [20]:
arr[:1,:2]

array([[1, 2]])

In [25]:
arr[1:3,2:4]

array([[4, 5],
       [6, 8]])

In [26]:
arr[1:3,2:5]

array([[4, 5, 6],
       [6, 8, 9]])

In [40]:
arr[2:3]

array([[9, 7, 6, 8, 9]])

In [44]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [49]:
arr[1:3,1:]

array([[3, 4, 5, 6],
       [7, 6, 8, 9]])

In [50]:
arr[:2, :3] # two rows three columns

array([[1, 2, 3],
       [2, 3, 4]])

In [53]:
arr[0:2,1:3]

array([[2, 3],
       [3, 4]])

In [59]:
arr[1:3,2:4] # arr[row(start):row(stop), column(start): column(stop)]

array([[4, 5],
       [6, 8]])

In [60]:
arr[1:3,1:4]

array([[3, 4, 5],
       [7, 6, 8]])

In [63]:
print(np.arange(0,10, 2))

[0 2 4 6 8]


In [65]:
np.linspace(1,10,50) # equally spaced point between the start n stop

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [73]:
# copy function and broad casting
arr1=np.array([1,2,3,4,5,6,7,8,9])

In [72]:
arr1[3:] = 100 # Broad casting

In [71]:
arr1

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [78]:
arr2 = arr1 # shallow copy, copy by reference

In [75]:
arr2[3:] = 500

In [76]:
arr2

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [77]:
arr1

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [79]:
arr3 = arr1.copy() # deep copy, copy by value

In [80]:
arr3[3:] = 600

In [81]:
arr3

array([  1,   2,   3, 600, 600, 600, 600, 600, 600])

In [82]:
arr1

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

 ## some conditions very useful in exploratory data analysis

In [83]:
val = 2
arr1[arr1<val]

array([1])

In [84]:
arr1<2

array([ True, False, False, False, False, False, False, False, False])

In [85]:
arr1 *2

array([   2,    4,    6, 1000, 1000, 1000, 1000, 1000, 1000])

In [86]:
arr /2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [1. , 1.5, 2. , 2.5, 3. ],
       [4.5, 3.5, 3. , 4. , 4.5]])

## create arrays and reshape

In [88]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [91]:
np.ones(4) # create new array with all one's, default data type is float

array([1., 1., 1., 1.])

In [93]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [95]:
np.ones((2,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
# Random distribution
np.random.rand